### PR TITLE
automated big parts of gating module and added additional functionalities

### PR DESCRIPTION
**Pull request by yungselm**
mainly worked in gating module, but added some functionalities to pop up windows and short cuts. Could you check for potentially dangerous code?

### CODE REVIEW

**Review by cardionaut — COMMENTED** [review]
Could move filter parameters to config file (in ContourBasedGating.__init__)
Otherwise looks good, will try to test later :)

**Comment by cardionaut** [comment]
Fixed some stuff - not sure whether some fixes were only necessary because of my package versions - please test.

Alt + S does not work properly if gating display is not already active, is this intended?
If intended, the shortcut should be disabled if gating display is inactive in my opinion.

Alt + Del removes all gated frames instead of asking for range in which to remove.

**Comment by yungselm** [comment]
For contour_based_gating: moved all parameters into config.file
Alt + Del: Fixed so it works with range
Alt + S: Unfortunately couldn't fix to being able to switch phases without display being active, therefore added a check if gating_display is active and otherwise throw an error message

**Comment by yungselm** [comment]
Added additional automatic detection by correlating starting frames with neighbouring frames. 
Things that still need fixing:
- class ContourBasedGating is too large and too convoluted
- If pop up box for starting frames gets closed, should run with only signal maxima
- Possibility to display the pop up window without contours
- save signals in .json? or report.txt? so that it's not calculated every time (but should recognize if config file was changed)

**Review by cardionaut — COMMENTED** [review]
super

**Pull request merged**
